version: "3.9"

services:
  investimentos-api:
    container_name: investimentos-api
    build:
      context: .
      dockerfile: InvestimentosJwtApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      # Volume persistente para o SQLite
      - ./data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
